if(require(tidyverse) == F) install.packages("tidyverse"); require(tidyverse)
if(require(here) == F) install.packages("here"); require(here)
if(require(readxl) == F) install.packages("readxl"); require(readxl)
if(require(openxlsx) == F) install.packages("openxlsx"); require(openxlsx)
if(require(scales) == F) install.packages("scales"); require(scales)
setwd(here("Bancos"))


# banco <- banco %>% 
#   transmute(id = ,
#             evento = ,
#             nome_pesquisador = ,
#             data_pesquisa = ,
#             resid_turista = ,
#             idade = ,
#             estado = ,
#             municipio = ,
#             pais = ,
#             pernoite = ,
#             cidade = ,
#             qtd_noite = ,
#             hospedagem = ,
#             transporte = ,
#             acesso = ,
#             rodovia = ,
#             hosp_rank = ,
#             gastronomia = ,
#             limpeza = ,
#             atividades = ,
#             outra_atividade = ,
#             motivo = ,
#             outra_motivo = ,
#             oficina = ,
#             interacao = ,
#             outra_atracao = ,
#             divulgacao = ,
#             nome_rede = ,
#             nome_rede_qual = ,
#             acompanhante = ,
#             outra_acompanhante = ,
#             gasto_alimento = ,
#             gasto_transp = ,
#             gasto_compras = ,
#             gasto_cultura = ,
#             qtd_gastos = ,
#             dia_evento = ,
#             avaliacao_local = ,
#             avaliacao_infra = ,
#             avaliacao_org = ,
#             avaliacao_divulg = ,
#             avaliacao_comida = ,
#             avaliacao_preco = ,
#             avaliacao_produtos = ,
#             avaliacao_prog = ,
#             avaliacao_representacao = ,
#             avaliacao_diversidade = ,
#             avaliacao_aproximacao = ,
#             avaliacao_acolhimento = ,
#             avaliacao_seguranca = ,
#             avaliacao_acessibilidade = ,
#             avaliacao_limpeza = ,
#             avaliacao_geral = ,
#             melhor_ativ = ,
#             volta = ,
#             sexo = ,
#             lgbt = ,
#             raca = ,
#             escolaridade = ,
#             renda = )



bh <- read_xls("BD_BH_STOCK_FESTIVAL_Pesquisa_em_rede.xls")

blumenau <- read_xlsx("Pesquisa Eventos BLUMENAU OKTOBERFEST.xlsx")

passira <- read_xlsx("Formulário Pesquisa em Rede - RBOT _ PASSIRA (respostas).xlsx")

virada <- read_xlsx("Virada 2024 Base de dados_Pesquisa_em_rede.xlsx")

congadas <- read_xlsx("BANCO DE DADOS - CONGADAS 2..xlsx")

natal_bem <- read_xlsx("BANCO DE DADOS Pesquisa em Rede RBOT_ Natal do BEM (respostas)..xlsx")

surubim <- read_xlsx("Formulário Pesquisa em Rede - RBOT (respostas SURUBIM).xlsx")

natal <- read_xlsx("Perfil do Visitante (NATAL) - RBOT (respostas).xlsx")

largo <- read_xlsx("PESQUISA EM REDE NATAL NO LARGO 2024 (respostas) (2).xlsx")

japao <- read_xlsx("PESQUISA EM REDE RBOT - Festival do Japão de Mato Grosso do Sul (respostas) (1).xlsx")

boi <- read_xlsx("PESQUISA EM REDE RBOT (respostas) (2).xlsx")

quixaba <- read_xlsx("Formulário Pesquisa em Rede - RBOT - Quixaba  (respostas).xlsx")

carnaval <- read_xlsx("Perfil do Visitante (CARNAVAL RN) - Rbot (respostas).xlsx")

martires <- read_xlsx("Perfil do Visitante (Mártires) - RBOT (respostas).xlsx")



passira <- passira %>% 
  transmute(id = `Carimbo de data/hora`,
            evento = `NOME DO EVENTO`,
            nome_pesquisador = `NOME DO PESQUISADOR`,
            data_pesquisa = `DATA DE PESQUISA`,
            resid_turista = `Você é ?
`,
            idade =`1. Qual sua idade? (maior de 16 anos)` ,
            estado = `2. Qual a sua residência permanente/onde você mora?`,
            municipio = `3. Se Pernambuco, qual município?`,
            pais = `4. Se “Outro país”, qual?`,
            pernoite = `5. Você pretende pernoitar (dormir) nesta cidade?`,
            cidade = `6. Qual outra cidade?`,
            qtd_noite = `7. Se sim, por quantos dias você pretende dormir nesta cidade?`,
            hospedagem = `8. Onde você pretende se hospedar?`,
            transporte = `9. Qual o meio de transporte utilizado para chegar ao destino?`,
            acesso = `10. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Acesso (rodovias)]`,
            rodovia = `10. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Sinalização (Rodovias)]`,
            hosp_rank = `10. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Hospedagem]`,
            gastronomia = `10. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Gastronomia/Restaurantes]`,
            limpeza = `10. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Limpeza Urbana]`,
            atividades = `11. Quais outras atividades você realizou ou pretende realizar nesta cidade?`,
            outra_atividade = `11.1 Se "Outro", qual?`,
            motivo = `12. Qual o principal motivo que fez você vir ao evento?`,
            outra_motivo = `12.1 Se "Outro", qual?`,
            oficina = `13. Você participou de alguma oficina cultural durante o festival?`,
            interacao = `14. O festival proporcionou uma oportunidade para você interagir com artistas e artesãos locais?`,
            outra_atracao = `15. Você participou ou visitou alguma outra atividade do evento além da atração principal?`,
            divulgacao = `16. Como você ficou sabendo do evento?`,
            nome_rede = `17. Se redes sociais e internet, qual rede e perfil? (Resposta Única e Espontânea)`,
            nome_rede_qual = `17.1 Se outro site ou perfil, qual?`,
            acompanhante = `18. Com quem você veio ao evento?`,
            outra_acompanhante = `18.1 Se "Outro", qual?`,
            gasto_alimento = `19. Qual será seu gasto estimado com alimentação:`,
            gasto_transp = `19.1. Qual será seu gasto estimado com transporte interno:`,
            gasto_compras = `19.2. Qual será seu gasto estimado com compras (feira):`,
            gasto_cultura = `19.3. Qual será seu gasto estimado com produtos e serviços culturais:`,
            qtd_gastos = `20. Contando com você, quantas pessoas estão incluídas nesses gastos?`,
            dia_evento = `21. Quantos dias participou ou irá participar do evento? (caso o evento seja apenas de um dia, esta pergunta já tem resposta automática de 1)`,
            avaliacao_local = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Local do evento]`,
            avaliacao_infra = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Infraestrutura do evento]`,
            avaliacao_org = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Organização do evento]`,
            avaliacao_divulg = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Divulgação]`,
            avaliacao_comida = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Alimentos e bebidas(qualidade)]`,
            avaliacao_preco = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Preços praticados no evento]`,
            avaliacao_produtos = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Artesanato e/ou Produtos comercializados]`,
            avaliacao_prog = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Programação cultural]`,
            avaliacao_representacao = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Representatividade da cultura local]`,
            avaliacao_diversidade = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Diversidade das atividades culturais]`,
            avaliacao_aproximacao = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Aproximação com a cultura local]`,
            avaliacao_acolhimento = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Acolhimento aos visitantes]`,
            avaliacao_seguranca = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Sensação de segurança]`,
            avaliacao_acessibilidade = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Acessibilidade /PCD no evento]`,
            avaliacao_limpeza = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Limpeza geral(ambiente evento)]`,
            avaliacao_geral = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Avaliação Geral do Evento]`,
            melhor_ativ = `23. Qual atividade cultural você mais gostou no evento?`,
            volta = `24. Você voltaria ao festival no próximo ano?`,
            sexo = `25. Qual sexo do respondente?`,
            lgbt = `26. Você é uma pessoa LGBTQIAPN+?`,
            raca = `27. Qual a sua identidade étnico racial?`,
            escolaridade = `28. Qual sua escolaridade?`,
            renda =`29. Sabendo que o salário mínimo é de R$ 1.420,00, sua renda familiar atual é de quantos salários mínimos? (cartão-resposta, opção de 1 a 8 ou mostra tablet e botão próxima)` )


quixaba <- quixaba %>% 
  transmute(id = `Carimbo de data/hora`,
            evento = `NOME DO EVENTO`,
            nome_pesquisador = `NOME DO PESQUISADOR`,
            data_pesquisa = `DATA DE PESQUISA`,
            resid_turista = `Você é ?
`,
            idade =`1. Qual sua idade? (maior de 16 anos)` ,
            estado = `2. Qual a sua residência permanente/onde você mora?`,
            municipio = `3. Se Pernambuco, qual município?`,
            pais = `4. Se “Outro país”, qual?`,
            pernoite = `5. Você pretende pernoitar (dormir) nesta cidade?`,
            cidade = `6. Qual outra cidade?`,
            qtd_noite = `7. Se sim, por quantos dias você pretende dormir nesta cidade?`,
            hospedagem = `8. Onde você pretende se hospedar?`,
            transporte = `9. Qual o meio de transporte utilizado para chegar ao destino?`,
            acesso = `10. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Acesso (rodovias)]`,
            rodovia = `10. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Sinalização (Rodovias)]`,
            hosp_rank = `10. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Hospedagem]`,
            gastronomia = `10. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Gastronomia/Restaurantes]`,
            limpeza = `10. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Limpeza Urbana]`,
            atividades = `11. Quais outras atividades você realizou ou pretende realizar nesta cidade?`,
            outra_atividade = `11.1 Se "Outro", qual?`,
            motivo = `12. Qual o principal motivo que fez você vir ao evento?`,
            outra_motivo = `12.1 Se "Outro", qual?`,
            oficina = `13. Você participou de alguma oficina cultural durante o festival?`,
            interacao = `14. O festival proporcionou uma oportunidade para você interagir com artistas e artesãos locais?`,
            outra_atracao = `15. Você participou ou visitou alguma outra atividade do evento além da atração principal?`,
            divulgacao = `16. Como você ficou sabendo do evento?`,
            nome_rede = `17. Se redes sociais e internet, qual rede e perfil? (Resposta Única e Espontânea)`,
            nome_rede_qual = `17.1 Se outro site ou perfil, qual?`,
            acompanhante = `18. Com quem você veio ao evento?`,
            outra_acompanhante = `18.1 Se "Outro", qual?`,
            gasto_alimento = `19. Qual será seu gasto estimado com alimentação:`,
            gasto_transp = `19.1. Qual será seu gasto estimado com transporte interno:`,
            gasto_compras = `19.2. Qual será seu gasto estimado com compras (feira):`,
            gasto_cultura = `19.3. Qual será seu gasto estimado com produtos e serviços culturais:`,
            qtd_gastos = `20. Contando com você, quantas pessoas estão incluídas nesses gastos?`,
            dia_evento = `21. Quantos dias participou ou irá participar do evento? (caso o evento seja apenas de um dia, esta pergunta já tem resposta automática de 1)`,
            avaliacao_local = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Local do evento]`,
            avaliacao_infra = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Infraestrutura do evento]`,
            avaliacao_org = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Organização do evento]`,
            avaliacao_divulg = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Divulgação]`,
            avaliacao_comida = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Alimentos e bebidas(qualidade)]`,
            avaliacao_preco = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Preços praticados no evento]`,
            avaliacao_produtos = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Artesanato e/ou Produtos comercializados]`,
            avaliacao_prog = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Programação cultural]`,
            avaliacao_representacao = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Representatividade da cultura local]`,
            avaliacao_diversidade = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Diversidade das atividades culturais]`,
            avaliacao_aproximacao = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Aproximação com a cultura local]`,
            avaliacao_acolhimento = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Acolhimento aos visitantes]`,
            avaliacao_seguranca = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Sensação de segurança]`,
            avaliacao_acessibilidade = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Acessibilidade /PCD no evento]`,
            avaliacao_limpeza = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Limpeza geral(ambiente evento)]`,
            avaliacao_geral = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Avaliação Geral do Evento]`,
            melhor_ativ = `23. Qual atividade cultural você mais gostou no evento?`,
            volta = `24. Você voltaria ao festival no próximo ano?`,
            sexo = `25. Qual sexo do respondente?`,
            lgbt = `26. Você é uma pessoa LGBTQIAPN+?`,
            raca = `27. Qual a sua identidade étnico racial?`,
            escolaridade = `28. Qual sua escolaridade?`,
            renda =`29. Sabendo que o salário mínimo é de R$ 1.420,00, sua renda familiar atual é de quantos salários mínimos? (cartão-resposta, opção de 1 a 8 ou mostra tablet e botão próxima)` )


surubim <- surubim %>% 
  transmute(id = `Carimbo de data/hora`,
            evento = `NOME DO EVENTO`,
            nome_pesquisador = `NOME DO PESQUISADOR`,
            data_pesquisa = `DATA DE PESQUISA`,
            resid_turista = `Você é ?
`,
            idade =`1. Qual sua idade? (maior de 16 anos)` ,
            estado = `2. Qual a sua residência permanente/onde você mora?`,
            municipio = `3. Se Pernambuco, qual município?`,
            pais = `4. Se “Outro país”, qual?`,
            pernoite = `5. Você pretende pernoitar (dormir) nesta cidade?`,
            cidade = `6. Qual outra cidade?`,
            qtd_noite = `7. Se sim, por quantos dias você pretende dormir nesta cidade?`,
            hospedagem = `8. Onde você pretende se hospedar?`,
            transporte = `9. Qual o meio de transporte utilizado para chegar ao destino?`,
            acesso = `10. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Acesso (rodovias)]`,
            rodovia = `10. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Sinalização (Rodovias)]`,
            hosp_rank = `10. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Hospedagem]`,
            gastronomia = `10. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Gastronomia/Restaurantes]`,
            limpeza = `10. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Limpeza Urbana]`,
            atividades = `11. Quais outras atividades você realizou ou pretende realizar nesta cidade?`,
            outra_atividade = `11.1 Se "Outro", qual?`,
            motivo = `12. Qual o principal motivo que fez você vir ao evento?`,
            outra_motivo = `12.1 Se "Outro", qual?`,
            oficina = `13. Você participou de alguma oficina cultural durante o festival?`,
            interacao = `14. O festival proporcionou uma oportunidade para você interagir com artistas e artesãos locais?`,
            outra_atracao = `15. Você participou ou visitou alguma outra atividade do evento além da atração principal?`,
            divulgacao = `16. Como você ficou sabendo do evento?`,
            nome_rede = `17. Se redes sociais e internet, qual rede e perfil? (Resposta Única e Espontânea)`,
            nome_rede_qual = `17.1 Se outro site ou perfil, qual?`,
            acompanhante = `18. Com quem você veio ao evento?`,
            outra_acompanhante = `18.1 Se "Outro", qual?`,
            gasto_alimento = `19. Qual será seu gasto estimado com alimentação:`,
            gasto_transp = `19.1. Qual será seu gasto estimado com transporte interno:`,
            gasto_compras = `19.2. Qual será seu gasto estimado com compras (feira):`,
            gasto_cultura = `19.3. Qual será seu gasto estimado com produtos e serviços culturais:`,
            qtd_gastos = `20. Contando com você, quantas pessoas estão incluídas nesses gastos?`,
            dia_evento = `21. Quantos dias participou ou irá participar do evento? (caso o evento seja apenas de um dia, esta pergunta já tem resposta automática de 1)`,
            avaliacao_local = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Local do evento]`,
            avaliacao_infra = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Infraestrutura do evento]`,
            avaliacao_org = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Organização do evento]`,
            avaliacao_divulg = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Divulgação]`,
            avaliacao_comida = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Alimentos e bebidas(qualidade)]`,
            avaliacao_preco = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Preços praticados no evento]`,
            avaliacao_produtos = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Artesanato e/ou Produtos comercializados]`,
            avaliacao_prog = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Programação cultural]`,
            avaliacao_representacao = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Representatividade da cultura local]`,
            avaliacao_diversidade = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Diversidade das atividades culturais]`,
            avaliacao_aproximacao = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Aproximação com a cultura local]`,
            avaliacao_acolhimento = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Acolhimento aos visitantes]`,
            avaliacao_seguranca = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Sensação de segurança]`,
            avaliacao_acessibilidade = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Acessibilidade /PCD no evento]`,
            avaliacao_limpeza = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Limpeza geral(ambiente evento)]`,
            avaliacao_geral = `22. Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 Não se aplica ou não sei [Avaliação Geral do Evento]`,
            melhor_ativ = `23. Qual atividade cultural você mais gostou no evento?`,
            volta = `24. Você voltaria ao festival no próximo ano?`,
            sexo = `25. Qual sexo do respondente?`,
            lgbt = `26. Você é uma pessoa LGBTQIAPN+?`,
            raca = `27. Qual a sua identidade étnico racial?`,
            escolaridade = `28. Qual sua escolaridade?`,
            renda =`29. Sabendo que o salário mínimo é de R$ 1.420,00, sua renda familiar atual é de quantos salários mínimos? (cartão-resposta, opção de 1 a 8 ou mostra tablet e botão próxima)` )

virada <- virada %>% 
  transmute(id = paste0("virada",row.names(virada)),
            evento = "virada",
            nome_pesquisador = NA,
            data_pesquisa = NA,
            resid_turista = `2. Qual a sua residência permanente/onde você mora?`,#alterar outra cidade e RMBH para turista
            idade = `1. Qual é a sua idade?`,
            estado = `2.2 Estado:`,
            municipio1 = `2.2 Outra cidade:`,
            municipio2 = `2.2 Cidade da região metropolitana de BH/RMBH:`,
            municipio3 = `2.2 Estado:`,
            pais = `2.1. Outro país:`,
            pernoite = `3. Você pretende pernoitar (dormir) em BH?`,
            cidade = NA,
            qtd_noite = `4. Se SIM, por quantos dias você pretende dormir na cidade?`,
            hospedagem = `5. Onde você pretende se hospedar?`,
            transporte = `6. Qual o meio de transporte utilizado para chegar à cidade?`,
            acesso = `I_1_P10 - (Acesso (Rodovias)) 10. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo a 1 (um) péssimo.`,
            rodovia = `I_2_P10 - (Sinalização (Rodovias)) 10. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo a 1 (um) péssimo.`,
            hosp_rank = `I_3_P10 - (Hospedagem) 10. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo a 1 (um) péssimo.`,
            gastronomia = `I_4_P10 - (Gastronomia/Restaurantes) 10. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo a 1 (um) péssimo.`,
            limpeza = `I_5_P10 - (Limpeza Urbana) 10. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo a 1 (um) péssimo.`,
            atividades = NA,
            outra_atividade = NA,
            motivo = `26. Qual principal motivo fez você vir ao evento?`,
            outra_motivo = NA,
            oficina = NA,
            interacao = NA,
            outra_atracao1 =`P14 a) PALCOS que foi ou pretende ir:` ,
            outra_atracao2 = `P14 b) ESPAÇOS que foi ou pretende ir:`,
            outra_atracao3 = `17. Você foi / pretende ir ao Viradão Gastronômico?`,
            divulgacao = `13. Como você ficou sabendo do evento?`,
            nome_rede = `13.1. Qual rede e perfil?`,
            nome_rede_qual = NA,
            acompanhante = `18. Com quem você veio à Virada?`,
            outra_acompanhante = NA,
            gasto_alimento = `Gasto individual com alimentação`,
            gasto_transp = `Gasto individual com transporte interno`,
            gasto_compras = `Gasto individual com produtos comercializados`,
            gasto_cultura = NA,
            qtd_gastos = NA,
            dia_evento = NA,
            avaliacao_local = `P19j) Avaliação: Localização dos pontos de intervenção e palcos`,
            avaliacao_infra = `P19n) Avaliação: Infraestrutura do evento`,
            avaliacao_org = `P19p) Avaliação: Organização`,
            avaliacao_divulg = `P19b) Avaliação: Divulgação`,
            avaliacao_comida = `P19g) Avaliação: Qualidade da alimentação (comida e bebida)`,
            avaliacao_preco = `P19i) Avaliação: Preços praticados na alimentação (comida e bebida)`,
            avaliacao_produtos = NA,
            avaliacao_prog = `P19s) Avaliação: Programação como um todo`,
            avaliacao_representacao = NA,
            avaliacao_diversidade = NA,
            avaliacao_aproximacao = NA,
            avaliacao_acolhimento = NA,
            avaliacao_seguranca = `P19m) Avaliação: Sensação de segurança`,
            avaliacao_acessibilidade = `P19l) Avaliação: Acessibilidade para pessoas com deficiência`,
            avaliacao_limpeza = `P19q) Avaliação: Limpeza das vias públicas`,
            avaliacao_geral = `P19a) Avaliação: Avaliação geral da Virada Cultural BH`,
            melhor_ativ = NA,
            volta = NA,
            sexo = `35. Com qual gênero você se identifica?`,
            lgbt = `37. Você é uma pessoa LGBTQIA+?`,
            raca = `32. Segundo as categorias do IBGE, como você declara sua cor ou raça?`,
            escolaridade = `34. Qual seu grau de escolaridade?`,
            renda =`38. Somando a sua renda com a renda das pessoas que moram na sua casa, em qual dessas faixas você se encontra?` )


natal_bem <- natal_bem %>% 
  transmute(id = `Carimbo de data/hora`,
            evento = "Natal do Bem",
            nome_pesquisador = Pesquisador,
            data_pesquisa = Data,
            resid_turista = `22. O entrevistado é turista, excursionista ou residente?`,
            idade = `1. Idade`,
            estado = `2. Qual sua origem? (UF)`,
            municipio = `3. Qual sua origem? (Cidade)`,
            pais = `2.1 País de origem`,
            pernoite = `3.1 Você pretende pernoitar em Goiânia?`,
            cidade = `4. Qual outra cidade?`,
            qtd_noite = `5. Quantos dias?`,
            hospedagem = `6. Onde você pretende se hospedar?`,
            transporte = `7. Qual o meio de transporte utilizado para chegar ao destino?`,
            acesso = `Acesso (Rodovias)`,
            rodovia = `Sinalização (Rodovias)`,
            hosp_rank = NA,
            gastronomia = `Gastronomia / Restaurantes`,
            limpeza = `Limpeza Urbana`,
            atividades = `9. Quais outras atividades você realizou ou pretende realizar nesta cidade?`,
            outra_atividade = NA,
            motivo = NA,
            outra_motivo = NA,
            oficina = `10. Você participou de alguma oficina cultural durante o festival?`,
            interacao = `11. O festival proporcionou uma oportunidade para você interagir com artistas e artesões locais?`,
            outra_atracao = `12. Você participou ou visitou alguma outra atividade do evento além da atração principal?`,
            divulgacao = `13. Como você ficou sabendo do evento?`,
            nome_rede = `14. Se redes sociais e internet, qual rede e perfil?`,
            nome_rede_qual = NA,
            acompanhante = `15. Com quem você veio ao evento?`,
            outra_acompanhante = NA,
            gasto_alimento = `Alimentação (Comida e bebida) - R$`,
            gasto_transp = `Transporte interno - R$`,
            gasto_compras = `Compras (Feira) - R$`,
            gasto_cultura = `Produtos e serviços culturais - R$`,
            qtd_gastos = `17. Contando com você, quantas pessoas estão incluídas nesses gastos?`,
            dia_evento = `18. Quantos dias participou ou irá participar do evento?`,
            avaliacao_local = `Local do Evento`,
            avaliacao_infra = `Infraestrutura do Evento`,
            avaliacao_org = `Organização do Evento`,
            avaliacao_divulg = Divulgação,
            avaliacao_comida = `Alimentos e bebidas (qualidade)`,
            avaliacao_preco = `Preços praticados no evento`,
            avaliacao_produtos = `Artesanato e/ou Produtos culturais comercializados`,
            avaliacao_prog = `Programação cultural`,
            avaliacao_representacao = `Representatividade da cultura local`,
            avaliacao_diversidade = `Diversidade das atividades culturais`,
            avaliacao_aproximacao = `Aproximação com a cultura local`,
            avaliacao_acolhimento = `Acolhimento aos visitantes`,
            avaliacao_seguranca = `Sensação de segurança`,
            avaliacao_acessibilidade = `Acessibilidade / PCD no evento`,
            avaliacao_limpeza = `Limpeza geral (ambiente evento)`,
            avaliacao_geral = `Avaliação Geral do Evento`,
            melhor_ativ = `20. Qual atividade cultural você mais gostou no evento?`,
            volta = `21. Você voltaria ao festival no próximo ano?`,
            sexo = `23. Qual sexo do respondente?`,
            lgbt = `24. Você é uma pessoa LGBTQIAPN+?`,
            raca = `25. Qual a sua identidade étnico racial?`,
            escolaridade = `26. Qual sua escolaridade?`,
            renda =`27. Renda familiar` )


natal <- natal %>% 
  transmute(id = `Carimbo de data/hora`,
            evento = "Natal",
            nome_pesquisador = NA,
            data_pesquisa = NA,
            resid_turista = `24. O entrevistado é turista, excursionista ou residente?`,
            idade = `1. Qual sua idade? (maior de 16 anos)`,
            estado = `2. Onde você reside?`,
            municipio = `3. Se "Rio Grande do Norte", qual município?`,
            pais = NA,
            pernoite = `4. Pretende pernoitar (dormir) nesta cidade?`,
            cidade = `5. Qual cidade?`,
            qtd_noite = `6. Se sim, por quantos dias você pretende dormir nessa cidade?`,
            hospedagem = `7. Onde você pretende se hospedar?`,
            transporte = `8. Qual o meio de transporte utilizado para chegar ao seu destino?`,
            acesso = `9. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo, a 1 (um) péssimo. (NS/NR sendo “Não se aplica” ou “não sei”)  [Acesso (rodovias)]`,
            rodovia = `9. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo, a 1 (um) péssimo. (NS/NR sendo “Não se aplica” ou “não sei”)  [Sinalização (rodovias)]`,
            hosp_rank = `9. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo, a 1 (um) péssimo. (NS/NR sendo “Não se aplica” ou “não sei”)  [Hospedagens]`,
            gastronomia = `9. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo, a 1 (um) péssimo. (NS/NR sendo “Não se aplica” ou “não sei”)  [Gastronomia/Restaurantes]`,
            limpeza = `9. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo, a 1 (um) péssimo. (NS/NR sendo “Não se aplica” ou “não sei”)  [Limpeza urbana  ]`,
            atividades = `10. Quais outras atividades você realizou ou pretende realizar nesta cidade?`,
            outra_atividade = NA,
            motivo = `11. Qual o principal motivo que fez você vir ao evento?`,
            outra_motivo = NA,
            oficina = `12. Você participou de alguma oficina cultural durante o festival?`,
            interacao = `13. O festival proporcionou uma oportunidade para você interagir com artistas e artesões locais?`,
            outra_atracao = NA,
            divulgacao = `15. Como você ficou sabendo do evento?`,
            nome_rede = `16. Se redes sociais, qual rede e qual perfil?`,
            nome_rede_qual = NA,
            acompanhante = `17. Com quem você veio ao evento?`,
            outra_acompanhante = NA,
            gasto_alimento = `18. Qual será seu gasto estimado no evento?  [Alimentação (comida e bebida)]`,
            gasto_transp = `18. Qual será seu gasto estimado no evento?  [Transporte interno ]`,
            gasto_compras = `18. Qual será seu gasto estimado no evento?  [Compras (feira)]`,
            gasto_cultura = `18. Qual será seu gasto estimado no evento?  [Produtos e serviços culturais]`,
            qtd_gastos = `19. Contando com você, quantas pessoas estão incluídas nesses gastos?`,
            dia_evento = `20. Quantos dias você participará/participou do evento?`,
            avaliacao_local = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Local do evento]`,
            avaliacao_infra = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Infraestrutura do evento]`,
            avaliacao_org = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Organização do evento]`,
            avaliacao_divulg = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Divulgação ]`,
            avaliacao_comida = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Alimentos e bebidas (qualidade)]`,
            avaliacao_preco = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Preços praticados no evento]`,
            avaliacao_produtos = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Preços praticados no evento]`,
            avaliacao_prog = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Programação cultural]`,
            avaliacao_representacao = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Representatividade da cultura local]`,
            avaliacao_diversidade = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Diversidades das atividades culturais]`,
            avaliacao_aproximacao = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Aproximação com a cultura local]`,
            avaliacao_acolhimento = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Acolhimento aos visitantes ]`,
            avaliacao_seguranca = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Sensação de segurança]`,
            avaliacao_acessibilidade = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Acessibilidade/PCD no evento]`,
            avaliacao_limpeza = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Limpeza geral (ambiente do evento)]`,
            avaliacao_geral = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Avaliação Geral do Evento]`,
            melhor_ativ = `22. Qual atividade cultural você mais gostou no evento?`,
            volta = `23. Você voltaria ao evento novamente?`,
            sexo = `25. Qual o gênero do respondente?`,
            lgbt = `26. Você faz parte da comunidade LGBTQIAPN+?`,
            raca = `27. Qual a sua identidade étnico racial?`,
            escolaridade = `28. Qual a sua escolaridade?`,
            renda = `29. Sabendo que o salário mínimo é de R$1.420,00, sua renda familiar atual é de quantos salários mínimos?`)


largo <- largo %>% 
  transmute(id = `Carimbo de data/hora`,
            evento = "Natal no Largo",
            nome_pesquisador = NA,
            data_pesquisa = NA,
            resid_turista = `O entrevistado é turista, excursionista ou residente?`,
            idade = `Qual a idade?`,
            estado = `Qual sua residência permanente/onde você mora?`,
            municipio = `Se "Amazonas", qual município?`,
            pais = NA,
            pernoite = `Você pretende pernoitar (dormir) nesta cidade?`,
            cidade = `Qual outra cidade?`,
            qtd_noite = `Se sim, por quantos dias você pretende dormir nesta cidade?`,
            hospedagem = `Onde você pretende se hospedar?`,
            transporte = `Qual meio de transporte utilizado para chegar ao destino?`,
            acesso = `Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ÓTIMO e 1 (um) PÉSSIMO [Acesso (rodovias)]`,
            rodovia = `Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ÓTIMO e 1 (um) PÉSSIMO [Sinalização (rodovias)]`,
            hosp_rank = `Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ÓTIMO e 1 (um) PÉSSIMO [Hospedagem]`,
            gastronomia = `Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ÓTIMO e 1 (um) PÉSSIMO [Gastronomia/Restaurante]`,
            limpeza = `Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ÓTIMO e 1 (um) PÉSSIMO [Limpeza urbana]`,
            atividades = `Quais outras atividades você realizou ou pretende realizar nesta cidade?`,
            outra_atividade = NA,
            motivo = `Qual o principal motivo que fez você vir ao evento?`,
            outra_motivo = NA,
            oficina = `Você participou de alguma oficina cultural durante o festival?`,
            interacao = `O festival proporcionou uma oportunidade para você interagir com artistas e artesãos locais?`,
            outra_atracao = `Você participou ou visitou alguma outra atividade do evento além da atração principal?
`,
            divulgacao = `Como você ficou sabendo do evento?`,
            nome_rede = `Se redes sociais e internet, qual rede e perfil?`,
            nome_rede_qual = NA,
            acompanhante = `Com quem você veio ao evento?`,
            outra_acompanhante = NA,
            gasto_alimento = NA,
            gasto_transp = NA,
            gasto_compras = NA,
            gasto_cultura = NA,
            qtd_gastos = `Contando você, quantas pessoas estão incluídas nesses gastos?`,
            dia_evento = `Quantos dias participou ou irá participar do evento?`,
            avaliacao_local = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Local]`,
            avaliacao_infra = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Infraestrutura]`,
            avaliacao_org = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Organização]`,
            avaliacao_divulg = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Divulgação]`,
            avaliacao_comida = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Alimentos e bebidas (qualidade)]`,
            avaliacao_preco = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Preços ]`,
            avaliacao_produtos = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Artesanato e/ou produtos culturais comercializados]`,
            avaliacao_prog = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Programação cultural]`,
            avaliacao_representacao = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Representatividade da cultura local]`,
            avaliacao_diversidade = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Diversidade das atividades culturais ]`,
            avaliacao_aproximacao = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Aproximação com a cultura local]`,
            avaliacao_acolhimento = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Acolhimento aos visitantes]`,
            avaliacao_seguranca = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Segurança]`,
            avaliacao_acessibilidade = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Acessibilidade/PCD ]`,
            avaliacao_limpeza = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Limpeza geral ]`,
            avaliacao_geral = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Avaliação geral]`,
            melhor_ativ = `Qual atividade cultural você mais gostou no evento?`,
            volta = `Você voltaria ao festival no próximo ano?`,
            sexo = `Qual o sexo do respondente?`,
            lgbt = `Você é uma pessoa LGBTQIAPN+?`,
            raca = `Qual a sua identidade étnico racial?`,
            escolaridade = `Qual sua escolaridade?`,
            renda = `Sabendo que o salário mínimo é de R$1.420,00, sua renda familiar atual é de até quantos salários mínimos?`)

colnames(japao) <- japao[2,]
japao <- japao[c(-1,-2),]  
japao <- japao %>% rename(acesso = 11, rodovia = 12, hosp_rank = 13, gastronomia = 14, limpeza = 15, interacao = 19,outra_atracao = 20) %>%   
  transmute(id = NA,
            evento = "Festival do Japão do Mato Grosso",
            nome_pesquisador = Aplicadores,
            data_pesquisa = `Data/hora`,
            resid_turista = `24.O entrevistado é turista, excursionista ou residente?`,
            idade = `1. Qual sua idade? (maior de 16 anos)`,
            estado = `2. Qual a sua residência permanente/onde você mora (Estado)?`,
            municipio = `3. Se “Mato Grosso do Sul”, qual município?`,
            pais = NA,
            pernoite = `4. Você pretende pernoitar (dormir) nesta cidade?`,
            cidade = `5. Qual outra cidade?`,
            qtd_noite = `6. Se sim, por quantos dias você pretende dormir nesta cidade? (ex: 1,2,3...)`,
            hospedagem = `7. Onde você pretende se hospedar?`,
            transporte = `8. Qual o meio de transporte utilizado para chegar ao destino?`,
            acesso ,
            rodovia ,
            hosp_rank ,
            gastronomia ,
            limpeza ,
            atividades = `10.Quais outras atividades você realizou ou pretende realizar nesta cidade?`,
            outra_atividade = NA,
            motivo = `11.Qual o principal motivo que fez você vir ao evento?`,
            outra_motivo = NA,
            oficina = `12.Você participou de alguma oficina cultural durante este festival?`,
            interacao ,
            outra_atracao ,
            divulgacao = `15. Como você ficou sabendo do evento?`,
            nome_rede = `16.Se redes sociais e internet, qual rede e perfil? (Resposta Única e Espontânea)`,
            nome_rede_qual = NA,
            acompanhante = `17.Com quem você veio ao evento?`,
            outra_acompanhante = NA,
            gasto_alimento = `Alimentação (Comida e bebida) R$`,
            gasto_transp = NA,
            gasto_compras = `Compras ( feira) R$`,
            gasto_cultura = `Produtos e serviços culturais R$`,
            qtd_gastos = `19.Contando com você, quantas pessoas estão incluídas nesses gastos? (numérico)`,
            dia_evento = `20.Quantos dias participou ou irá participar do evento?`,
            avaliacao_local = `21.Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (0 “Não se aplica” ou “não sei”) [a. Local do evento]`,
            avaliacao_infra = `21.Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (0 “Não se aplica” ou “não sei”) [b. Infraestrutura do evento]`,
            avaliacao_org = `21.Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (0 “Não se aplica” ou “não sei”) [c. Organização do evento]`,
            avaliacao_divulg = `21.Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (0 “Não se aplica” ou “não sei”) [d. Divulgação]`,
            avaliacao_comida = `21.Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (0 “Não se aplica” ou “não sei”) [e. Alimentos e bebidas(qualidade)]`,
            avaliacao_preco = `21.Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (0 “Não se aplica” ou “não sei”) [f. Preços praticados no evento]`,
            avaliacao_produtos = `21.Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (0 “Não se aplica” ou “não sei”) [g. Artesanato e/ou Produtos culturais comercializados]`,
            avaliacao_prog = `21.Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (0 “Não se aplica” ou “não sei”) [h. Programação cultural]`,
            avaliacao_representacao = `21.Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (0 “Não se aplica” ou “não sei”) [i. Representatividade da cultura local]`,
            avaliacao_diversidade = `21.Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (0 “Não se aplica” ou “não sei”) [j. Diversidade das atividades culturais]`,
            avaliacao_aproximacao = `21.Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (0 “Não se aplica” ou “não sei”) [k. Aproximação com a cultura local]`,
            avaliacao_acolhimento = `21.Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (0 “Não se aplica” ou “não sei”) [l. Acolhimento aos visitantes]`,
            avaliacao_seguranca = `21.Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (0 “Não se aplica” ou “não sei”) [m. Sensação de segurança]`,
            avaliacao_acessibilidade = `21.Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (0 “Não se aplica” ou “não sei”) [n. Acessibilidade /PCD no evento]`,
            avaliacao_limpeza = `21.Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (0 “Não se aplica” ou “não sei”) [o. Limpeza geral(ambiente evento)]`,
            avaliacao_geral = `21.Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (0 “Não se aplica” ou “não sei”) [p. Avaliação Geral do Evento]`,
            melhor_ativ = `22.Qual atividade cultural você mais gostou no evento?`,
            volta = `23.Você voltaria ao "Festival do Japão” no próximo ano?`,
            sexo = `25.Qual sexo do respondente?`,
            lgbt = `26.Você é uma pessoa LGBTQIAPN+?`,
            raca = `27.Qual a sua identidade étnico racial?`,
            escolaridade = `28.Qual sua escolaridade?`,
            renda = `29.Sabendo que o salário mínimo é de R$ 1.420,00, sua renda familiar atual é de quantos salários mínimos?`)


congadas <- congadas %>% 
  transmute(id = `Carimbo de data/hora`,
            evento = "Congadas",
            nome_pesquisador = Pesquisador,
            data_pesquisa = Data,
            resid_turista = `24. O entrevistado é turista, excursionista ou residente?`,
            idade = `1. Idade`,
            estado = `2. Qual sua origem? (UF)`,
            municipio = `3. Qual sua origem? (Cidade)`,
            pais = `2.1 País de origem`,
            pernoite = `3.1 Você pretende pernoitar em Ouvidor?`,
            cidade = `3.2 Vou pernoitar em outra cidade?`,
            qtd_noite = `5. Quantos dias?`,
            hospedagem = `6. Onde você pretende se hospedar?`,
            transporte = `7. Qual o meio de transporte utilizado para chegar ao destino?`,
            acesso = `Acesso (Rodovias)`,
            rodovia = `Sinalização (Rodovias)`,
            hosp_rank = NA,
            gastronomia = `Gastronomia / Restaurantes`,
            limpeza = `Limpeza Urbana`,
            atividades = `10. Quais outras atividades você realizou ou pretende realizar nesta cidade?`,
            outra_atividade = NA,
            motivo = NA,
            outra_motivo = NA,
            oficina = `12. Você participou de alguma oficina cultural durante o festival?`,
            interacao = `13. O festival proporcionou uma oportunidade para você interagir com artistas e artesões locais?`,
            outra_atracao = `14. Você participou ou visitou alguma outra atividade do evento além da atração principal?`,
            divulgacao = `15. Como você ficou sabendo do evento?`,
            nome_rede = `16. Se redes sociais e internet, qual rede e perfil?`,
            nome_rede_qual = NA,
            acompanhante = `17. Com quem você veio ao evento?`,
            outra_acompanhante = NA,
            gasto_alimento = `Alimentação (Comida e bebida) - R$`,
            gasto_transp = `Transporte interno - R$`,
            gasto_compras = `Compras (Feira) - R$`,
            gasto_cultura = `Produtos e serviços culturais - R$`,
            qtd_gastos = `19. Contando com você, quantas pessoas estão incluídas nesses gastos?`,
            dia_evento = `20. Quantos dias participou ou irá participar do evento?`,
            avaliacao_local = `Local do Evento`,
            avaliacao_infra = `Infraestrutura do Evento`,
            avaliacao_org = `Organização do Evento`,
            avaliacao_divulg = Divulgação,
            avaliacao_comida = `Alimentos e bebidas (qualidade)`,
            avaliacao_preco = `Preços praticados no evento`,
            avaliacao_produtos = `Artesanato e/ou Produtos culturais comercializados`,
            avaliacao_prog = `Programação cultural`,
            avaliacao_representacao = `Representatividade da cultura local`,
            avaliacao_diversidade = `Diversidade das atividades culturais`,
            avaliacao_aproximacao = `Aproximação com a cultura local`,
            avaliacao_acolhimento = `Acolhimento aos visitantes`,
            avaliacao_seguranca = `Sensação de segurança`,
            avaliacao_acessibilidade = `Acessibilidade / PCD no evento`,
            avaliacao_limpeza = `Limpeza geral (ambiente evento)`,
            avaliacao_geral = `Avaliação Geral do Evento`,
            melhor_ativ = `22. Qual atividade cultural você mais gostou no evento?`,
            volta = `23. Você voltaria ao festival no próximo ano?`,
            sexo = `25. Qual sexo do respondente?`,
            lgbt = `26. Você é uma pessoa LGBTQIAPN+?`,
            raca = `27. Qual a sua identidade étnico racial?`,
            escolaridade = `28. Qual sua escolaridade?`,
            renda = `29. Renda familiar`)



boi <- boi %>%
  transmute(id = `Carimbo de data/hora`,
            evento = "Boi Manaus",
            nome_pesquisador = NA,
            data_pesquisa = NA,
            resid_turista = `O entrevistado é turista, excursionista ou residente?`,
            idade = `Qual a idade?`,
            estado = `Qual sua residência permanente/onde você mora?`,
            municipio = `Se "Amazonas", qual município?`,
            pais = NA,
            pernoite = `Você pretende pernoitar (dormir) nesta cidade?`,
            cidade = `Qual outra cidade?`,
            qtd_noite = `Se sim, por quantos dias você pretende dormir nesta cidade?`,
            hospedagem = `Onde você pretende se hospedar?`,
            transporte = `Qual meio de transporte utilizado para chegar ao destino?`,
            acesso = `Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ÓTIMO e 1 (um) PÉSSIMO [Acesso (rodovias)]`,
            rodovia = `Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ÓTIMO e 1 (um) PÉSSIMO [Sinalização (rodovias)]`,
            hosp_rank = `Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ÓTIMO e 1 (um) PÉSSIMO [Hospedagem]`,
            gastronomia = `Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ÓTIMO e 1 (um) PÉSSIMO [Gastronomia/Restaurante]`,
            limpeza = `Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ÓTIMO e 1 (um) PÉSSIMO [Limpeza urbana]`,
            atividades = `Quais outras atividades você realizou ou pretende realizar nesta cidade?`,
            outra_atividade = NA,
            motivo = `Qual o principal motivo que fez você vir ao evento?`,
            outra_motivo = NA,
            oficina = `Você participou de alguma oficina cultural durante o festival?`,
            interacao = `O festival proporcionou uma oportunidade para você interagir com artistas e artesãos locais?`,
            outra_atracao = `Você participou ou visitou alguma outra atividade do evento além da atração principal?
`,
            divulgacao = `Como você ficou sabendo do evento?`,
            nome_rede = `Se redes sociais e internet, qual rede e perfil?`,
            nome_rede_qual = NA,
            acompanhante = `Com quem você veio ao evento?`,
            outra_acompanhante = NA,
            gasto_alimento = NA,
            gasto_transp = NA,
            gasto_compras = NA,
            gasto_cultura = NA,
            qtd_gastos = `Contando você, quantas pessoas estão incluídas nesses gastos?`,
            dia_evento = `Quantos dias participou ou irá participar do evento?`,
            avaliacao_local = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Local]`,
            avaliacao_infra = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Infraestrutura]`,
            avaliacao_org = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Organização]`,
            avaliacao_divulg = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Divulgação]`,
            avaliacao_comida = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Alimentos e bebidas (qualidade)]`,
            avaliacao_preco = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Preços ]`,
            avaliacao_produtos = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Artesanato e/ou produtos culturais comercializados]`,
            avaliacao_prog = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Programação cultural]`,
            avaliacao_representacao = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Representatividade da cultura local]`,
            avaliacao_diversidade = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Diversidade das atividades culturais ]`,
            avaliacao_aproximacao = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Aproximação com a cultura local]`,
            avaliacao_acolhimento = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Acolhimento aos visitantes]`,
            avaliacao_seguranca = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Segurança]`,
            avaliacao_acessibilidade = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Acessibilidade/PCD ]`,
            avaliacao_limpeza = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Limpeza geral ]`,
            avaliacao_geral = `Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ÓTIMO e 1 (um) péssimo [Avaliação geral]`,
            melhor_ativ = `Qual atividade cultural você mais gostou no evento?`,
            volta = `Você voltaria ao festival no próximo ano?`,
            sexo = `Qual o sexo do respondente?`,
            lgbt = `Você é uma pessoa LGBTQIAPN+?`,
            raca = `Qual a sua identidade étnico racial?`,
            escolaridade = `Qual sua escolaridade?`,
            renda = `Sabendo que o salário mínimo é de R$1.420,00, sua renda familiar atual é de até quantos salários mínimos?`)

blumenau <- blumenau %>%
  transmute(id = `ID de resposta`,
            evento = "BLUMENAU OKTOBERFEST",
            nome_pesquisador = NA,
            data_pesquisa = NA,
            resid_turista = `O entrevistado é turista, excursionista ou residente ?`,
            idade = `Qual sua idade ? (Deve ser maior de 16 anos) `,
            estado = `Qual ESTADO é sua residência permanente/onde você mora?`,
            municipio = `Se Santa Catarina, qual município?`,
            pais = `Se “Outro país”, qual ? `,
            pernoite = `Você pretende pernoitar (dormir) nesta cidade ? `,
            cidade = `Qual outra cidade? `,
            qtd_noite = `Se sim, por quantos dias você pretende dormir nesta cidade?`,
            hospedagem = `Onde você pretende se hospedar ? `,
            transporte = `Qual o meio de transporte utilizado para chegar ao destino ?`,
            acesso = `Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) Ótimo a 1 (um) Péssimo.  0 (zero) Não se aplica/ Não sei  Acesso (Rodovias)`,
            rodovia = `Sinalização (Rodovias) `,
            hosp_rank = `Hospedagem `,
            gastronomia = `Gastronomia/Restaurantes`,
            limpeza = `Limpeza Urbana  `,
            atividades = `Quais outras atividades você realizou ou pretende realizar nesta cidade ? `,
            outra_atividade = NA,
            motivo = `Qual o principal motivo que fez você vir ao evento ? `,
            outra_motivo = NA,
            oficina = `Você participou de alguma oficina cultural durante o festival?`,
            interacao = `O festival proporcionou uma oportunidade para você interagir com artistas e artesãos locais?`,
            outra_atracao = `Você participou ou visitou alguma outra atividade do evento além da atração principal ?`,
            divulgacao = `Como você ficou sabendo do evento ? `,
            nome_rede = `Se redes sociais e internet, qual rede e perfil? (Resposta Única e Espontânea) `,
            nome_rede_qual = `Anotar o perfil falado`,
            acompanhante = `Com quem você veio ao evento ?`,
            outra_acompanhante = NA,
            gasto_alimento = NA,
            gasto_transp = `Transporte interno R$`,
            gasto_compras = `Compras ( feira) R$`,
            gasto_cultura = `Produtos e serviços culturais R$ `,
            qtd_gastos = `Contando com você, quantas pessoas estão incluídas nesses gastos ?`,
            dia_evento = `Quantos dias participou ou irá participar do evento ? (caso o evento seja apenas de um dia, esta pergunta já tem resposta automática de 1)`,
            avaliacao_local = `Avalie os seguintes aspectos relacionados ao evento deste ano,  pontuando de 10 (dez) ótimo a 1 (um) péssimo.  0 (Zero) Não se aplica/Não seiLocal do evento `,
            avaliacao_infra = `Infraestrutura do evento`,
            avaliacao_org = `Organização do evento `,
            avaliacao_divulg = Divulgação,
            avaliacao_comida = `Alimentos e bebidas (qualidade)`,
            avaliacao_preco = `Preços praticados no evento`,
            avaliacao_produtos = `Produtos e serviços culturais R$ `,
            avaliacao_prog = `Programação cultural `,
            avaliacao_representacao = `Representatividade da cultura local`,
            avaliacao_diversidade = `Diversidade das atividades culturais`,
            avaliacao_aproximacao = `Aproximação com a cultura local`,
            avaliacao_acolhimento = `Acolhimento aos visitantes`,
            avaliacao_seguranca = `Sensação de segurança `,
            avaliacao_acessibilidade = `Acessibilidade /PCD no evento `,
            avaliacao_limpeza = `Limpeza geral (ambiente evento)`,
            avaliacao_geral = `Avaliação Geral do Evento `,
            melhor_ativ = `Qual atividade cultural você mais gostou no evento ? `,
            volta = `Você voltaria ao festival “Oktoberfest Blumenau” no próximo ano?`,
            sexo = `Qual sexo do respondente ?`,
            lgbt = `Você é uma pessoa LGBTQIAPN+ ?`,
            raca = `Qual a sua identidade étnico racial ?`,
            escolaridade = `Qual sua escolaridade?`,
            renda = `Sabendo que o Salário Mínimo (SM) é de R$ 1.420,00, sua renda familiar atual é de quantos salários mínimos ? `)

virada <- virada %>% mutate(municipio3 = NULL,
                            municipio = case_when(is.na(estado)== F ~ municipio1,
                                                  TRUE ~ municipio2), municipio1 = NULL,
                            municipio2 = NULL)
virada <- virada %>% mutate(outra_atracao1 = NULL,
                            outra_atracao = case_when(is.na(outra_atracao2)== FALSE~"Sim",
                                                      outra_atracao3 == "Sim, fui ou pretendo ir"~"Sim",
                                                      outra_atracao3 == "Ainda não decidiu"~"NR/NS",
                                                      TRUE ~"Não"))

virada <- virada %>% mutate(outra_atracao2 = NULL, outra_atracao3 = NULL)

carnaval <- carnaval %>%
  transmute(id = `Carimbo de data/hora`,
            evento = "Carnaval RN",
            nome_pesquisador = NA,
            data_pesquisa = NA,
            resid_turista = `24. O entrevistado é turista, excursionista ou residente?`,
            idade = `1. Qual sua idade? (maior de 16 anos)`,
            estado = `2. Onde você reside?`,
            municipio = `3. Se "Rio Grande do Norte", qual município?`,
            pais = NA,
            pernoite = `4. Pretende pernoitar (dormir) nesta cidade?`,
            cidade = `5. Qual cidade?`,
            qtd_noite = `6. Se sim, por quantos dias você pretende dormir nessa cidade?`,
            hospedagem = `7. Onde você pretende se hospedar?`,
            transporte = `8. Qual o meio de transporte utilizado para chegar ao seu destino?`,
            acesso = `9. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo, a 1 (um) péssimo. (NS/NR sendo “Não se aplica” ou “não sei”)  [Acesso (rodovias)]`,
            rodovia = `9. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo, a 1 (um) péssimo. (NS/NR sendo “Não se aplica” ou “não sei”)  [Sinalização (rodovias)]`,
            hosp_rank = `9. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo, a 1 (um) péssimo. (NS/NR sendo “Não se aplica” ou “não sei”)  [Hospedagens]`,
            gastronomia = `9. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo, a 1 (um) péssimo. (NS/NR sendo “Não se aplica” ou “não sei”)  [Gastronomia/Restaurantes]`,
            limpeza = `9. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo, a 1 (um) péssimo. (NS/NR sendo “Não se aplica” ou “não sei”)  [Limpeza urbana  ]`,
            atividades = `10. Quais outras atividades você realizou ou pretende realizar nesta cidade?`,
            outra_atividade = NA,
            motivo = `11. Qual o principal motivo que fez você vir ao evento?`,
            outra_motivo = NA,
            oficina = `12. Você participou de alguma oficina cultural durante o festival?`,
            interacao = `13. O festival proporcionou uma oportunidade para você interagir com artistas e artesões locais?`,
            outra_atracao = `14. Você participou ou visitou alguma outra atividade do evento além da atração principal?`,
            divulgacao = `15. Como você ficou sabendo do evento?`,
            nome_rede = `16. Se redes sociais, qual rede e qual perfil?`,
            nome_rede_qual = NA,
            acompanhante = `17. Com quem você veio ao evento?`,
            outra_acompanhante = NA,
            gasto_alimento = `18. Qual será seu gasto estimado no evento?  [Alimentação (comida e bebida)]`,
            gasto_transp = `18. Qual será seu gasto estimado no evento?  [Transporte interno ]`,
            gasto_compras = `18. Qual será seu gasto estimado no evento?  [Compras (feira)]`,
            gasto_cultura = `18. Qual será seu gasto estimado no evento?  [Produtos e serviços culturais]`,
            qtd_gastos = `19. Contando com você, quantas pessoas estão incluídas nesses gastos?`,
            dia_evento = `20. Quantos dias você participará/participou do evento?`,
            avaliacao_local = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Local do evento]`,
            avaliacao_infra = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Infraestrutura do evento]`,
            avaliacao_org = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Organização do evento]`,
            avaliacao_divulg = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Divulgação ]`,
            avaliacao_comida = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Alimentos e bebidas (qualidade)]`,
            avaliacao_preco = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Preços praticados no evento]`,
            avaliacao_produtos = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Artesanato e/ou produtos culturais comercializados ]`,
            avaliacao_prog = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Programação cultural]`,
            avaliacao_representacao = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Representatividade da cultura local]`,
            avaliacao_diversidade = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Diversidades das atividades culturais]`,
            avaliacao_aproximacao = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Aproximação com a cultura local]`,
            avaliacao_acolhimento = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Acolhimento aos visitantes ]`,
            avaliacao_seguranca = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Sensação de segurança]`,
            avaliacao_acessibilidade = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Acessibilidade/PCD no evento]`,
            avaliacao_limpeza = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Limpeza geral (ambiente do evento)]`,
            avaliacao_geral = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Avaliação Geral do Evento]`,
            melhor_ativ = `22. Qual atividade cultural você mais gostou no evento?`,
            volta = `23. Você voltaria ao evento novamente?`,
            sexo = `25. Qual o gênero do respondente?`,
            lgbt = `26. Você faz parte da comunidade LGBTQIAPN+?`,
            raca = `27. Qual a sua identidade étnico racial?`,
            escolaridade = `28. Qual a sua escolaridade?`,
            renda = `29. Sabendo que o salário mínimo é de R$1.420,00, sua renda familiar atual é de quantos salários mínimos?`)





martires <- martires %>%
  transmute(id = `Carimbo de data/hora`,
            evento = "Festa de Martires",
            nome_pesquisador = NA,
            data_pesquisa = NA,
            resid_turista = `24. O entrevistado é turista, excursionista ou residente?`,
            idade = `1. Qual sua idade? (maior de 16 anos)`,
            estado = `2. Onde você reside?`,
            municipio = `3. Se "Rio Grande do Norte", qual município?`,
            pais = NA,
            pernoite = `4. Pretende pernoitar (dormir) nesta cidade?`,
            cidade = `5. Qual cidade?`,
            qtd_noite = `6. Se sim, por quantos dias você pretende dormir nessa cidade?`,
            hospedagem = `7. Onde você pretende se hospedar?`,
            transporte = `8. Qual o meio de transporte utilizado para chegar ao seu destino?`,
            acesso = `9. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo, a 1 (um) péssimo. (NS/NR sendo “Não se aplica” ou “não sei”)  [Acesso (rodovias)]`,
            rodovia = `9. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo, a 1 (um) péssimo. (NS/NR sendo “Não se aplica” ou “não sei”)  [Sinalização (rodovias)]`,
            hosp_rank = `9. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo, a 1 (um) péssimo. (NS/NR sendo “Não se aplica” ou “não sei”)  [Hospedagens]`,
            gastronomia = `9. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo, a 1 (um) péssimo. (NS/NR sendo “Não se aplica” ou “não sei”)  [Gastronomia/Restaurantes]`,
            limpeza = `9. Avalie os seguintes aspectos relacionados à cidade, pontuando de 10 (dez) ótimo, a 1 (um) péssimo. (NS/NR sendo “Não se aplica” ou “não sei”)  [Limpeza urbana  ]`,
            atividades = `10. Quais outras atividades você realizou ou pretende realizar nesta cidade?`,
            outra_atividade = NA,
            motivo = `11. Qual o principal motivo que fez você vir ao evento?`,
            outra_motivo = NA,
            oficina = `12. Você participou de alguma oficina cultural durante o festival?`,
            interacao = `13. O festival proporcionou uma oportunidade para você interagir com artistas e artesões locais?`,
            outra_atracao = `14. Você participou ou visitou alguma outra atividade do evento além da atração principal?`,
            divulgacao = `15. Como você ficou sabendo do evento?`,
            nome_rede = `16. Se redes sociais, qual rede e qual perfil?`,
            nome_rede_qual = NA,
            acompanhante = `17. Com quem você veio ao evento?`,
            outra_acompanhante = NA,
            gasto_alimento = `18. Qual será seu gasto estimado no evento?  [Alimentação (comida e bebida)]`,
            gasto_transp = `18. Qual será seu gasto estimado no evento?  [Transporte interno ]`,
            gasto_compras = `18. Qual será seu gasto estimado no evento?  [Compras (feira)]`,
            gasto_cultura = `18. Qual será seu gasto estimado no evento?  [Produtos e serviços culturais]`,
            qtd_gastos = `19. Contando com você, quantas pessoas estão incluídas nesses gastos?`,
            dia_evento = `20. Quantos dias você participará/participou do evento?`,
            avaliacao_local = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Local do evento]`,
            avaliacao_infra = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Infraestrutura do evento]`,
            avaliacao_org = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Organização do evento]`,
            avaliacao_divulg = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Divulgação ]`,
            avaliacao_comida = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Alimentos e bebidas (qualidade)]`,
            avaliacao_preco = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Preços praticados no evento]`,
            avaliacao_produtos = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Artesanato e/ou produtos culturais comercializados ]`,
            avaliacao_prog = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Programação cultural]`,
            avaliacao_representacao = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Representatividade da cultura local]`,
            avaliacao_diversidade = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Diversidades das atividades culturais]`,
            avaliacao_aproximacao = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Aproximação com a cultura local]`,
            avaliacao_acolhimento = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Acolhimento aos visitantes ]`,
            avaliacao_seguranca = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Sensação de segurança]`,
            avaliacao_acessibilidade = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Acessibilidade/PCD no evento]`,
            avaliacao_limpeza = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Limpeza geral (ambiente do evento)]`,
            avaliacao_geral = `21. Avalie os seguintes aspectos relacionados ao evento deste ano, pontuando de 10 (dez) ótimo a 1 (um) péssimo. (NS/NR - "não se aplica" ou "não sei") [Avaliação Geral do Evento]`,
            melhor_ativ = `22. Qual atividade cultural você mais gostou no evento?`,
            volta = `23. Você voltaria ao evento novamente?`,
            sexo = `25. Qual o gênero do respondente?`,
            lgbt = `26. Você faz parte da comunidade LGBTQIAPN+?`,
            raca = `27. Qual a sua identidade étnico racial?`,
            escolaridade = `28. Qual a sua escolaridade?`,
            renda = `29. Sabendo que o salário mínimo é de R$1.420,00, sua renda familiar atual é de quantos salários mínimos?`)



dic <- read_xlsx("dicionario_blumenau.xlsx")

# Get the sheet names
sheet_names <- excel_sheets("dicionario_blumenau.xlsx")

# Read all sheets into a named list
data_list <- setNames(lapply(sheet_names, function(sheet) {
  read_excel("dicionario_blumenau.xlsx", sheet = sheet)
}), sheet_names)

rm(blumenal)

blumenau <- blumenau %>% left_join(data_list$estado) %>% left_join(data_list$pernoite) %>% 
  left_join(data_list$nome_rede) %>% left_join(data_list$transporte) %>% left_join(data_list$atividade) %>% 
  left_join(data_list$divulgacao) %>% left_join(data_list$hospedagem) %>% left_join(data_list$motivo) %>% 
  left_join(data_list$oficina) %>% left_join(data_list$interacao) %>% left_join(data_list$outra_atracao) %>% 
  left_join(data_list$acompanhante) %>% left_join(data_list$renda) %>% left_join(data_list$volta) %>% 
  left_join(data_list$sexo) %>% left_join(data_list$resid_turista) %>% left_join(data_list$lgbt) %>% 
  left_join(data_list$raca) %>% left_join(data_list$escolaridade)

blumenau <- blumenau %>% select(-pernoite,-estado,-nome_rede,-transporte,-atividades,-divulgacao,-hospedagem,-motivo,-oficina,
                                -interacao,-outra_atracao,-acompanhante,-renda,-volta,-sexo,-resid_turista,-lgbt,-raca,
                                -escolaridade)

colnames(blumenau) <- gsub("_new","",colnames(blumenau))




rbot <- rbind(
  virada %>% mutate(uf_evento = "MG", mun_evento = "Belo Horizonte"),
  surubim %>% mutate(uf_evento = "PE", mun_evento = "Surubim", evento = "Semana Cultural"),
  quixaba %>% mutate(uf_evento = "PE", mun_evento = "Quixaba", evento = "95 Janeiro Fest"),
  passira %>% mutate(uf_evento = "PE", mun_evento = "Passira", evento = "36 FEBOMAP"),
  natal_bem %>% mutate(uf_evento = "GO", mun_evento = "Goiania"),
  natal %>% mutate(uf_evento = "RN", mun_evento = "Natal"),
  largo %>% mutate(uf_evento = "AM", mun_evento = "Manaus"),
  japao %>% mutate(uf_evento = "MT", mun_evento = "Campo Grande"),
  congadas %>% mutate(uf_evento = "GO", mun_evento = "Ouvidor"),
  boi %>% mutate(uf_evento = "AM", mun_evento = "Manaus"),
  blumenau %>% mutate(uf_evento = "SC", mun_evento = "Blumenau"),
  martires %>% mutate(uf_evento = "RN", mun_evento = "Natal"),
  carnaval %>% mutate(uf_evento = "RN", mun_evento = "Natal")
  
)

write.xlsx(rbot,"rbot.xlsx")


rbot <- rbot  %>% filter(evento!= "Semana Cultural")
rbot <- rbot %>% mutate(id =paste0("rbot-",rownames(rbot)),nome_pesquisador=NULL,data_pesquisa=NULL)
rbot <- rbot %>% mutate(resid_turista = case_when(resid_turista == "Belo Horizonte"~"Residente",
                                  resid_turista == "Cidade da região metropolitana de BH/RMBH"~"Excursionista",
                                  resid_turista == "Outro país" | resid_turista == "Outra cidade"~"Turista",
                                  is.na(resid_turista)== TRUE~"Não responderam",
                                  TRUE~resid_turista))


rbot <- rbot %>% mutate(idade2=as.numeric(gsub(" anos|anos|Anos| Anos| anos de idade","",idade)),
                        idade2 = case_when(idade2 < 17 ~ "eliminar",
                                           idade2>=17&idade2<=20~"17 a 20 anos",
                                           idade2>=21&idade2<=40~"21 a 40 anos",
                                           idade2>=41&idade2<=50~"41 a 50 anos",
                                           idade2>=51&idade<=60~"51 a 60 anos",
                                           idade2>60~"Acima de 60 anos", TRUE~NA),
                        idade=case_when(is.na(idade2)==TRUE~idade,
                                        TRUE~idade2),
                        idade=ifelse(idade%in%c("Não responderam","Filipe","Carnaíba","Água Branca pb",
                                                   "Princesa Isabel","eliminar"),NA,idade),
                        idade2=NULL, 
                        idade=case_when(idade== "60.0"|idade == "60 anos"~"51 a 60 anos",
                                        idade == "60+"~"Acima de 60 anos", TRUE~ idade))
  
d <- data.frame(estado = unique(rbot$estado),
                estado_new= c(NA, "Minas Gerais", "São Paulo", "Rio de Janeiro", "Ceará",
                              "Bahia", "Distrito Federal", "Paraná", "Paraíba", "Pernambuco",
                              "Maranhão", "Rio Grande do Norte", "Distrito Federal",
                              "Rondônia", "Piauí", "Alagoas", "Santa Catarina", "Goiás",
                              "Sergipe", "Outro país", "Goiás", "Pará", "Rondônia", "Distrito Federal",
                              NA, "Minas Gerais", "São Paulo", "Tocantins", "Mato Grosso", "Maranhão",
                              "Santa Catarina", "Rio de Janeiro", "Amazonas", "Outro país", "Amazonas", "Amazonas",
                              NA, "Amazonas", "Amazonas", "Amazonas", "Amazonas",
                              "Tocantins", "Pará", NA, "Pernambuco", "Roraima",
                              "Mato Grosso do Sul", "São Paulo", "Minas Gerais",
                              "Outro país", "Mato Grosso", "Rio de Janeiro", "Outro país",
                              "Acre", "Outro país", "Pernambuco", "Outro país",
                              "Outro país", "Rio Grande do Sul", "Mato Grosso", "Outro país",
                              "Mato Grosso do Sul", "Espírito Santo", "Distrito Federal"))
rbot <- rbot %>% mutate(pais = ifelse(estado%in%c("Árabe - Líbano","Portugal","Itália","Merida/México","Roma","Venezuela"),estado,pais)) %>% 
  left_join(d,by = "estado") %>% mutate(estado = estado_new,
                                                       estado_new = NULL)
rbot <- rbot %>% mutate(estado = case_when(estado == "Outro país"~NA, TRUE ~ estado))

rbot <- rbot %>% mutate(pais = case_when(pais == "Jaboatão dos outros" ~ NA,
                                         pais == "Jaboatão dos Guararapes"~NA,
                                         pais == "Jurú"~NA,
                                         pais == "Princesa Isabel"~ NA,
                                         pais == "Nr"~ NA,
                                         pais == "Ns"~ NA,
                                         pais == "Não"~NA,
                                         pais == "Nao sei"~NA,
                                         pais =="Merida/México"~ "México",
                                         pais == "Roma"~"Itália",
                                         pais == "Árabe - Líbano"~ "Libano",
                                         TRUE ~ pais))

rbot <- rbot %>% mutate(pernoite = case_when(pernoite == "Sim (pular para a questão 7)"~"Sim",
                                             pernoite == "Sim (pular para a 7)"~"Sim",
                                             pernoite%in%c("Não vai pernoitar","Não (pular para a questão 8)","Não vai pernoitar (pular para a 9)","Vou pernoitar em outra cidade.",
                                                           "Não vai pernoitar ","Não (pular para a questão 9)","Não vai pernoitar (pular para 8)")~"Não",
                                             TRUE~NA))

rbot <- rbot %>% mutate(cidade = case_when(cidade == "-"~NA,
                                           cidade == "Ns"~NA,
                                           cidade == "Não quis informar"~NA,
                                           cidade == "Não se aplica"~NA,
                                           cidade == "Não se aplica (Morador/turista cidadão)"~NA,
                                           cidade%in%c(".","casa","Não se aplica (Pernoite em Ouvidor)","3.0","SGA","Não tem","Sim","Não responderam","Não","Nr","Não quis responder",
                                                       "4.0","Nao sei")~NA,
                                           cidade=="Carnaiba PE"~"Carnaiba",
                                           cidade=="Limoeiro-Pe"~"Limoeiro",
                                           cidade=="Balnerio Camboriú"~"Balneário",
                                           cidade=="Em Carnaiba PE, na casa de meu tio"~"Carnaíba",
                                           cidade=="Sou de Natal rn, mas vou para Fernando Pedroza"~"Fernando Pedroza",
                                           cidade=="Natap"~"Natal",
                                           cidade=="Natal1"~"Natal",
                                           cidade=="Alminio afonso"~"Almino Afonso",
                                           cidade=="Natal rn"~"Natal",
                                           cidade=="Praia de Caraúbas, Maxaranguape"~"Maxaranguape",
                                           cidade=="Touros/RN"~"Touros",
                                           cidade=="Natal RN"~"Natal RN",
                                           cidade=="Frecheirinha ce"~"Freceirinha",
                                           cidade=="Praia de Jacumã - Ceará Mirim/RN"~"Ceará Mirim",
                                           cidade=="Tibau do sul/RN"~"Tibau do sul",
                                           cidade=="Extremoz (residente)"~"Extremoz",
                                           cidade=="Parnamirim- Pirangi"~"Parnamirim",
                                           cidade=="Campina Grande - PB"~"Campina Grande",
                                           cidade=="Natal RN"~"Natal",
                                           cidade=="Rio Grande Do norte natal"~"Natal",
                                           cidade=="parnamirim"~"Parnamirim",
                                           cidade=="Caicó e Macau"~"Caicó",
                                           cidade=="Pirangi- Parnamirim"~"Parnamirim",
                                           cidade=="Zumbi, Rio do Fogo"~"Rio do Fogo",
                                           cidade=="Caruaru, Recife"~"Caruaru",
                                           cidade=="Tavares Paraíba"~"Tavares",
                                           cidade=="Ceará Mirim"~"Ceará-Mirim",
                                           cidade=="Muriu"~"Muriú",
                                           cidade=="natal"~"Natal",
                                           cidade=="PARAZINHO"~"Parazinho",
                                           cidade=="Poço de pedra"~"Poço de Pedra",
                                           cidade=="São gonçalo"~"São Gonçalo",
                                           cidade=="São Gonçalo do ama"~"São Gonçalo do Amarante",
                                           T~cidade))

q <- data.frame(qtd_noite = unique(rbot$qtd_noite),
                qtd_noite_new= c(NA,"1","15","2","7","4","3","5","15","10","10","30","30",NA,"20",NA,"15","2",
                                 "20","4","30","8","1","14","18",NA,"5","2","2",NA,"9","30",NA,"18","18","15","12","25","8","14",NA,"7","5","3",
                                 "21","12","18","360","90","18",NA,NA,NA,NA,NA,"16",NA,NA,NA,"21",NA,NA,"7","11","16",NA,"8",NA,NA,NA,"13",NA,NA,NA,
                                 "14","7","19","6",NA,"22","3",NA,NA,"3","1","7",NA,NA,NA,NA,NA,NA,"4",NA,NA,NA,"2",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,"0",
                                 NA,NA,"8","10",NA,NA,"7",NA,NA,NA,NA,"30",NA,"17",NA,NA,"0",NA,NA,"6",NA,NA,NA,NA,NA,NA,"1",NA,NA,NA,"2",NA,"4",NA,NA,
                                 NA,NA,NA,NA,NA,NA,NA,NA,"6",NA,"7",NA,NA,NA,NA,"15",NA,NA,NA))

